on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.jonathangillette.net
        FTP_USERNAME: ftp_jonathan@jonathangillette.net
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD_PROD }}
        REMOTE_DIR: keystoneconcertband.com
        ARGS: --delete --dry-run --no-empty-dirs --exclude-glob=.git/* --exclude-glob=.github/*
        # --delete arg will delete files on the server if you've deleted them in git
